name: my first workflow
on:
  push:
    branches:
      - main
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5.0.0

      - name: Run script
        run: ./script.sh