name: Docker CI/CD

on: push

env:
  DOCKER_USERNAME: 201950748
  IMAGE_NAME: github-actions-nginx
  CONTAINER_REGISTRY: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Docker Login
        run: echo docker login --username=${{ env.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    # concurrency:
    #   group: shazly-deployment
    #   cancel-in-progress: true
    
    steps:
      - name: docker run
        run: |
          echo "Would run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
          echo "Simulating 10 minute deployment..."
          sleep 10s
