name: Matrix Strategy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [17, 18]
    steps:
        - name: Print env info
          run: |
            echo "OS: ${{ matrix.os }}"
            echo "Node.js version: ${{ matrix.node-version }}"
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}

        - name: Run commands
          run: |
            node -v